CC=gcc
OBJ=more01.o more02.o more03.o more04.o more05.o cp1.o
CFLAGS=-g3
display:
more01:
more02:
more03:
more04:
more05:
cp1:
cp2:
.PHONY:clean
clean:
	-rm -rf *.o
	-rm -rf more01 more02 more03 more04 more05
	-rm -rf cp1 cp2 
	-rm -rf display
