CC=gcc
CFLAGS=-g3
OBJ=ls1.o ls2.o ls3.c filesize.o fileinfo.o myfile.o myfinger.o mychown.o
mychown:
myfinger:
myfile:
ls1:
ls2:
ls3:
filesize:
fileinfo:
.PHONY:clean
clean:
	-rm $(OBJ)
	-rm ls1 ls2 ls3 myfile myfinger mychown
	-rm filesize
	-rm fileinfo
