CC=gcc
 
rotate:rotate.o
	$(CC) -o $@ $^
play_again:play_again.o
	$(CC) -o $@ $^
play_again1:play_again1.o
	$(CC) -o $@ $^
play_again2:play_again2.o
	$(CC) -o $@ $^
play_again3:play_again3.o
	$(CC) -o $@ $^
sigdemo1:sigdemo1.o
	$(CC) -o $@ $^
sigdemo2:sigdemo2.o
	$(CC) -o $@ $^
.PHONY:clean
clean:
	-rm -rf *.o
	-rm rotate 
	-rm play_again play_again1 play_again2 play_again3
	-rm sigdemo1 sigdemo2
