
#
#	makefile for programs in lecture 8
#

psh1: psh1.c
	cc psh1.c -o psh1

psh2: psh2.c
	cc psh2.c -o psh2

forkdemo: forkdemo.c
	cc forkdemo.c -o forkdemo

lsenv: lsenv.c
	cc lsenv.c -o lsenv

smsh1: smsh1.o shelllib.o envlib.o
	cc smsh1.o shelllib.o envlib.o -o smsh1
