#
# makefile for the small shell series
#

LIBS = varlib.o splitline.o
CC   = gcc 

smsh1: smsh1.o $(LIBS)
	cc -o smsh1 smsh1.o $(LIBS)

smsh2: smsh2.o $(LIBS)
	cc -o smsh2 smsh2.o $(LIBS)

smsh3: smsh3.o $(LIBS)
	cc -o smsh3 smsh3.o $(LIBS)

smsh4: smsh4.o $(LIBS)
	cc -o smsh4 smsh4.o $(LIBS)

